name: Build with Nuitka on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # 適用於你的應用的 Python 版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install numpy nibabel # 安裝你的 Python 應用所需的依賴
        # 安裝 MinGW 編譯器
        choco install mingw

    - name: Compile with Nuitka
      run: |
        nuitka --standalone --onefile --mingw64 --output-dir=dist example.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-executable
        path: dist/
